"""add Share model

Revision ID: 040a90a5a35c
Revises: 6210e4e54fb8
Create Date: 2025-06-12 02:06:24.000047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040a90a5a35c'
down_revision = '6210e4e54fb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_analytics',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_likes_received', sa.Integer(), nullable=True),
    sa.Column('total_comments_received', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('share', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_actor_id'), ['actor_id'], unique=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_user_id'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_actor_id'))

    with op.batch_alter_table('share', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_user_id'))
        batch_op.drop_index(batch_op.f('ix_share_timestamp'))
        batch_op.drop_index(batch_op.f('ix_share_post_id'))
        batch_op.drop_index(batch_op.f('ix_share_group_id'))

    op.drop_table('share')
    op.drop_table('user_analytics')
    # ### end Alembic commands ###
