"""manual_alter_virtualgood_string_lengths

Revision ID: 08e875156728
Revises: f2c60380cec8
Create Date: 2025-06-18 11:05:52.508972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08e875156728'
down_revision = 'f2c60380cec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtual_good', schema=None) as batch_op:
        batch_op.alter_column('title_text',
               existing_type=sa.String(),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('title_icon_url',
               existing_type=sa.String(),
               type_=sa.String(length=2048),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtual_good', schema=None) as batch_op:
        batch_op.alter_column('title_icon_url',
               existing_type=sa.String(length=2048),
               type_=sa.String(),
               nullable=True)
        batch_op.alter_column('title_text',
               existing_type=sa.String(length=255),
               type_=sa.String(),
               nullable=True)
    # ### end Alembic commands ###
