"""add tip model

Revision ID: 0eb35e9d47dd
Revises: 08e875156728
Create Date: 2025-08-08 11:19:35.769258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eb35e9d47dd'
down_revision = '08e875156728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipper_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tipper_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tip', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tip_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tip_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tip_stripe_payment_intent_id'), ['stripe_payment_intent_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_tip_tipper_id'), ['tipper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tip_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tip', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tip_timestamp'))
        batch_op.drop_index(batch_op.f('ix_tip_tipper_id'))
        batch_op.drop_index(batch_op.f('ix_tip_stripe_payment_intent_id'))
        batch_op.drop_index(batch_op.f('ix_tip_status'))
        batch_op.drop_index(batch_op.f('ix_tip_recipient_id'))

    op.drop_table('tip')
    # ### end Alembic commands ###
