"""Add criteria_key to Badge model

Revision ID: 39c237ff4a68
Revises: 27ee689df10d
Create Date: 2025-06-18 01:10:51.631528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c237ff4a68'
down_revision = '27ee689df10d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criteria_key', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint("uq_badge_criteria_key", ['criteria_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.drop_constraint("uq_badge_criteria_key", type_='unique')
        batch_op.drop_column('criteria_key')

    # ### end Alembic commands ###
