"""Add VirtualGood and UserVirtualGood models

Revision ID: 662475da4e7d
Revises: e03445f75a10
Create Date: 2025-06-14 01:27:11.972208

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '662475da4e7d'
down_revision = 'e03445f75a10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtual_good',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_virtual_good',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('virtual_good_id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_equipped', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['virtual_good_id'], ['virtual_good.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'virtual_good_id', name='_user_virtual_good_uc')
    )
    with op.batch_alter_table('user_virtual_good', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_virtual_good_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_virtual_good_virtual_good_id'), ['virtual_good_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_virtual_good', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_virtual_good_virtual_good_id'))
        batch_op.drop_index(batch_op.f('ix_user_virtual_good_user_id'))

    op.drop_table('user_virtual_good')
    op.drop_table('virtual_good')
    # ### end Alembic commands ###
