"""Add title_text and title_icon_url to VirtualGood

Revision ID: 6d2cbc810521
Revises: dbacd35de3b9
Create Date: 2025-06-18 10:14:34.425022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d2cbc810521'
down_revision = 'dbacd35de3b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stream_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stream_chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stream_chat_messages_stream_id'), ['stream_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stream_chat_messages_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_stream_chat_messages_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('live_streams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_live_streams_is_live'))
        batch_op.create_index(batch_op.f('ix_live_streams_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_streams_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_streams_status'), ['status'], unique=False)
        batch_op.drop_column('is_live')

    with op.batch_alter_table('virtual_good', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_text', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('title_icon_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtual_good', schema=None) as batch_op:
        batch_op.drop_column('title_icon_url')
        batch_op.drop_column('title_text')

    with op.batch_alter_table('live_streams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_live', sa.BOOLEAN(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_live_streams_status'))
        batch_op.drop_index(batch_op.f('ix_live_streams_start_time'))
        batch_op.drop_index(batch_op.f('ix_live_streams_end_time'))
        batch_op.create_index(batch_op.f('ix_live_streams_is_live'), ['is_live'], unique=False)
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('status')

    with op.batch_alter_table('stream_chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stream_chat_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_stream_chat_messages_timestamp'))
        batch_op.drop_index(batch_op.f('ix_stream_chat_messages_stream_id'))

    op.drop_table('stream_chat_messages')
    # ### end Alembic commands ###
