"""add_scheduling_fields_to_post_and_story

Revision ID: 7ebedbdd0d36
Revises: 956a4c9b90ee
Create Date: 2025-06-13 10:10:23.535170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ebedbdd0d36'
down_revision = '956a4c9b90ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - START OF RELEVANT POST CHANGES ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_for', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.create_index(batch_op.f('ix_post_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_scheduled_for'), ['scheduled_for'], unique=False)
    # ### commands auto generated by Alembic - END OF RELEVANT POST CHANGES ###

    # ### commands auto generated by Alembic - START OF RELEVANT STORY CHANGES ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_for', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.create_index(batch_op.f('ix_story_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_scheduled_for'), ['scheduled_for'], unique=False)
    # ### commands auto generated by Alembic - END OF RELEVANT STORY CHANGES ###


def downgrade():
    # ### commands auto generated by Alembic - START OF RELEVANT STORY CHANGES ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_scheduled_for'))
        batch_op.drop_index(batch_op.f('ix_story_is_published'))
        batch_op.drop_column('is_published')
        batch_op.drop_column('scheduled_for')
    # ### commands auto generated by Alembic - END OF RELEVANT STORY CHANGES ###

    # ### commands auto generated by Alembic - START OF RELEVANT POST CHANGES ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_scheduled_for'))
        batch_op.drop_index(batch_op.f('ix_post_is_published'))
        batch_op.drop_column('is_published')
        batch_op.drop_column('scheduled_for')
    # ### commands auto generated by Alembic - END OF RELEVANT POST CHANGES ###
