"""Add point_price to VirtualGood model

Revision ID: a1397fa0a290
Revises: corrective_script
Create Date: 2025-06-19 00:32:51.932447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1397fa0a290'
down_revision = 'corrective_script'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stream_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stream_chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stream_chat_messages_stream_id'), ['stream_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stream_chat_messages_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_stream_chat_messages_user_id'), ['user_id'], unique=False)

    op.create_table('moderation_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_taken', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('related_post_id', sa.Integer(), nullable=True),
    sa.Column('related_comment_id', sa.Integer(), nullable=True),
    sa.Column('moderation_service_response', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['related_comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['related_post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('moderation_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moderation_log_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pending_moderation', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_hidden_by_moderation', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_comments_is_hidden_by_moderation'), ['is_hidden_by_moderation'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_is_pending_moderation'), ['is_pending_moderation'], unique=False)

    with op.batch_alter_table('live_streams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_live_streams_is_live'))
        batch_op.create_index(batch_op.f('ix_live_streams_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_streams_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_streams_status'), ['status'], unique=False)
        batch_op.drop_column('is_live')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pending_moderation', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_hidden_by_moderation', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_post_is_hidden_by_moderation'), ['is_hidden_by_moderation'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_is_pending_moderation'), ['is_pending_moderation'], unique=False)

    with op.batch_alter_table('user_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_points_level'), ['level'], unique=False)

    with op.batch_alter_table('virtual_good', schema=None) as batch_op:
        batch_op.add_column(sa.Column('point_price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtual_good', schema=None) as batch_op:
        batch_op.drop_column('point_price')

    with op.batch_alter_table('user_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_points_level'))
        batch_op.drop_column('level')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_is_pending_moderation'))
        batch_op.drop_index(batch_op.f('ix_post_is_hidden_by_moderation'))
        batch_op.drop_column('is_hidden_by_moderation')
        batch_op.drop_column('is_pending_moderation')

    with op.batch_alter_table('live_streams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_live', sa.BOOLEAN(), server_default=sa.text('(false)'), nullable=False))
        batch_op.drop_index(batch_op.f('ix_live_streams_status'))
        batch_op.drop_index(batch_op.f('ix_live_streams_start_time'))
        batch_op.drop_index(batch_op.f('ix_live_streams_end_time'))
        batch_op.create_index(batch_op.f('ix_live_streams_is_live'), ['is_live'], unique=False)
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('status')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_is_pending_moderation'))
        batch_op.drop_index(batch_op.f('ix_comments_is_hidden_by_moderation'))
        batch_op.drop_column('is_hidden_by_moderation')
        batch_op.drop_column('is_pending_moderation')

    with op.batch_alter_table('moderation_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moderation_log_timestamp'))

    op.drop_table('moderation_log')
    with op.batch_alter_table('stream_chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stream_chat_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_stream_chat_messages_timestamp'))
        batch_op.drop_index(batch_op.f('ix_stream_chat_messages_stream_id'))

    op.drop_table('stream_chat_messages')
    # ### end Alembic commands ###
