"""add paid posts feature

Revision ID: a1b2c3d4e5f6
Revises: 0eb35e9d47dd
Create Date: 2025-08-08 09:50:20.179381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '0eb35e9d47dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto-generated by Alembic - please adjust! ###
    op.create_table('post_purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency_paid', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='_user_post_purchase_uc')
    )
    with op.batch_alter_table('post_purchase', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_purchase_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_purchase_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto-generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('currency')
        batch_op.drop_column('price')

    with op.batch_alter_table('post_purchase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_purchase_user_id'))
        batch_op.drop_index(batch_op.f('ix_post_purchase_post_id'))

    op.drop_table('post_purchase')
    # ### end Alembic commands ###
