"""corrective_revert_unrelated_stream_changes_from_6d2cbc810521

Revision ID: corrective_script
Revises: 08e875156728
Create Date: YYYY-MM-DD HH:MM:SS.MS

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'corrective_script'
down_revision = '08e875156728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('stream_chat_messages')
    with op.batch_alter_table('live_streams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_live', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False))
        batch_op.drop_index(batch_op.f('ix_live_streams_status'))
        batch_op.drop_index(batch_op.f('ix_live_streams_start_time'))
        batch_op.drop_index(batch_op.f('ix_live_streams_end_time'))
        batch_op.create_index(batch_op.f('ix_live_streams_is_live'), ['is_live'], unique=False)
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate stream_chat_messages table (structure from 6d2cbc810521)
    op.create_table('stream_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stream_id'], ['live_streams.id'], name=op.f('fk_stream_chat_messages_stream_id_live_streams')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_stream_chat_messages_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stream_chat_messages'))
    )
    with op.batch_alter_table('stream_chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stream_chat_messages_stream_id'), ['stream_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stream_chat_messages_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_stream_chat_messages_user_id'), ['user_id'], unique=False)

    # Revert changes to live_streams table
    with op.batch_alter_table('live_streams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default=sa.text("'upcoming'"), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))
        # Ensure the index name matches what would be dropped if it was created by this batch_op context for consistency
        # However, since it's being dropped, the table_name argument is crucial if the index name isn't specific to batch_op.
        # For safety, assuming the auto-generated name 'ix_live_streams_is_live' might not be batch_op specific in all contexts.
        batch_op.drop_index(batch_op.f('ix_live_streams_is_live'))
        batch_op.create_index(batch_op.f('ix_live_streams_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_streams_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_streams_status'), ['status'], unique=False)
        batch_op.drop_column('is_live')
    # ### end Alembic commands ###
