"""Add related_item_type to ActivityLog

Revision ID: dbacd35de3b9
Revises: 39c237ff4a68
Create Date: 2025-06-18 09:26:46.702370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbacd35de3b9'
down_revision = '39c237ff4a68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_item_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_column('related_item_type')

    # ### end Alembic commands ###
