"""Add HashtagUsage model

Revision ID: e73ee734fd74
Revises: e1c4b3a68c13
Create Date: 2025-07-23 08:49:30.715431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e73ee734fd74'
down_revision = 'e1c4b3a68c13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtag_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashtag_id', sa.Integer(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hashtag_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hashtag_usage_hashtag_id'), ['hashtag_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hashtag_usage_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hashtag_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hashtag_usage_timestamp'))
        batch_op.drop_index(batch_op.f('ix_hashtag_usage_hashtag_id'))

    op.drop_table('hashtag_usage')
    # ### end Alembic commands ###
