"""Add active_title_id to User model

Revision ID: f2c60380cec8
Revises: 6d2cbc810521
Create Date: 2025-06-18 10:15:43.634612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2c60380cec8'
down_revision = '6d2cbc810521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_title_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_active_title_id_user_virtual_good', 'user_virtual_good', ['active_title_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_active_title_id_user_virtual_good', type_='foreignkey')
        batch_op.drop_column('active_title_id')

    # ### end Alembic commands ###
