"""Add Stripe ID fields to User, SubscriptionPlan, and UserSubscription models

Revision ID: manual_0002_add_stripe_ids
Revises: manual_0001_add_subscription_models
Create Date: 2025-06-13 23:04:23.594127

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'manual_0002_add_stripe_ids'
down_revision = 'manual_0001_add_subscription_models'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add to User table
    op.add_column('user', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_user_stripe_customer_id'), 'user', ['stripe_customer_id'], unique=True)

    # Add to SubscriptionPlan table
    op.add_column('subscription_plan', sa.Column('stripe_product_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_subscription_plan_stripe_product_id'), 'subscription_plan', ['stripe_product_id'], unique=False)
    op.add_column('subscription_plan', sa.Column('stripe_price_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_subscription_plan_stripe_price_id'), 'subscription_plan', ['stripe_price_id'], unique=True)

    # Add to UserSubscription table
    op.add_column('user_subscription', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_user_subscription_stripe_subscription_id'), 'user_subscription', ['stripe_subscription_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert UserSubscription table
    op.drop_index(op.f('ix_user_subscription_stripe_subscription_id'), table_name='user_subscription')
    op.drop_column('user_subscription', 'stripe_subscription_id')

    # Revert SubscriptionPlan table
    op.drop_index(op.f('ix_subscription_plan_stripe_price_id'), table_name='subscription_plan')
    op.drop_column('subscription_plan', 'stripe_price_id')
    op.drop_index(op.f('ix_subscription_plan_stripe_product_id'), table_name='subscription_plan')
    op.drop_column('subscription_plan', 'stripe_product_id')

    # Revert User table
    op.drop_index(op.f('ix_user_stripe_customer_id'), table_name='user')
    op.drop_column('user', 'stripe_customer_id')
    # ### end Alembic commands ###
