"""Add is_active to SubscriptionPlan model

Revision ID: manual_0003_add_is_active_to_subscription_plan
Revises: manual_0002_add_stripe_ids
Create Date: 2025-06-13 23:14:20.047350

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'manual_0003_add_is_active_to_subscription_plan'
down_revision = 'manual_0002_add_stripe_ids'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_plan', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.create_index(op.f('ix_subscription_plan_is_active'), 'subscription_plan', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_plan_is_active'), table_name='subscription_plan')
    op.drop_column('subscription_plan', 'is_active')
    # ### end Alembic commands ###
