"""Add SubscriptionPlan and UserSubscription models

Revision ID: manual_0001_add_subscription_models
Revises: e03445f75a10
Create Date: 2025-06-13 23:01:19.762477

"""
from alembic import op
import sqlalchemy as sa
# from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'manual_0001_add_subscription_models'
down_revision = 'e03445f75a10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plan',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('creator_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('currency', sa.String(length=3), nullable=False),
        sa.Column('duration', sa.String(length=50), nullable=False),
        sa.Column('features', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plan_creator_id'), 'subscription_plan', ['creator_id'], unique=False)

    op.create_table('user_subscription',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('subscriber_id', sa.Integer(), nullable=False),
        sa.Column('plan_id', sa.Integer(), nullable=False),
        sa.Column('start_date', sa.DateTime(), nullable=False),
        sa.Column('end_date', sa.DateTime(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('payment_details_id', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['plan_id'], ['subscription_plan.id'], ),
        sa.ForeignKeyConstraint(['subscriber_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_subscription_plan_id'), 'user_subscription', ['plan_id'], unique=False)
    op.create_index(op.f('ix_user_subscription_status'), 'user_subscription', ['status'], unique=False)
    op.create_index(op.f('ix_user_subscription_subscriber_id'), 'user_subscription', ['subscriber_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_subscription_subscriber_id'), table_name='user_subscription')
    op.drop_index(op.f('ix_user_subscription_status'), table_name='user_subscription')
    op.drop_index(op.f('ix_user_subscription_plan_id'), table_name='user_subscription')
    op.drop_table('user_subscription')

    op.drop_index(op.f('ix_subscription_plan_creator_id'), table_name='subscription_plan')
    op.drop_table('subscription_plan')
    # ### end Alembic commands ###
